# Copyright 2013-2018 Alexander Peslyak
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

CC = gcc
LD = $(CC)
RM = rm -f
OMPFLAGS = -fopenmp
OMPFLAGS_MAYBE = $(OMPFLAGS)
CFLAGS = -Wall -O2 -march=native -fomit-frame-pointer $(OMPFLAGS_MAYBE) -DSKIP_MEMZERO
LDFLAGS = -s -lrt $(OMPFLAGS_MAYBE)

PROJ = tests
CORE = yescrypt-opt
LIB_CORE = lib$(CORE).so
OBJS_CORE = $(CORE).o
OBJS_COMMON = yescrypt-common.o sha256.o insecure_memzero.o
OBJS_TESTS = $(OBJS_COMMON) tests.o
LDLIBS = -L. -l$(CORE)
OBJS_RM = yescrypt-*.o
TESTS_FILE = TESTS-OPT.log

all: $(PROJ)

check: tests
	@echo 'Running main tests'
	@time ./tests | tee $(TESTS_FILE)

ref:
	$(MAKE) $(PROJ) CORE=yescrypt-ref

check-ref:
	$(MAKE) check CORE=yescrypt-ref TESTS_FILE=TESTS-REF.log 

tests: $(OBJS_TESTS) $(LIB_CORE)
	export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH
	$(LD) $(LDFLAGS) $(OBJS_TESTS) $(LDLIBS) -o $@

.c.o:
	$(CC) -c $(CFLAGS) -fPIC $*.c

yescrypt-opt.o: yescrypt-platform.c

$(LIB_CORE): $(OBJS_CORE)
	$(CC) -shared -o $@ $<

clean:
	$(RM) $(PROJ)
	$(RM) $(OBJS_TESTS)
	$(RM) $(OBJS_RM)
	$(RM) TESTS-OUT PHC-TEST-OUT
	$(RM) libyescrypt-opt.so
	$(RM) libyescrypt-ref.so
